# CUDA_VISIBLE_DEVICES=1 python render.py --model_path pretrain_checkpoint/pre_trained_gaussians/endonerf/cutting --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/endonerf/cutting_tissues_twice
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path pretrain_checkpoint/pre_trained_gaussians/endonerf/pulling --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/endonerf/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path output/endonerf/pulling_ss --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/endonerf/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path output/endonerf/cutting_ss --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/endonerf/cutting_tissues_twice
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p1_1_split3r_test" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p1_1
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_test" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/cutting_split3r_v4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/cutting_tissues_twice
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p1_1_split3r_v4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p1_1
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_5_1_split3r_v4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_5_1
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_8_1_split3r_v4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_8_1
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p3_1_split3r_v4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p3_1
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_test" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues

# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_offset" --pc --skip_test --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/cutting_split3r_v4_offset" --pc --skip_test --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/cutting_tissues_twice
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p1_1_split3r_v4_offset" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p1_1
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_offset" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_5_1_split3r_v4_offset" --pc --skip_test --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_5_1
# # CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_8_1_split3r_v4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_8_1
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p3_1_split3r_v4_offset" --pc --skip_test --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p3_1

# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_pretrain" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_pixeldiff" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_pretrain" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_pixeldiff" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2

# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_1pcd" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_1pcd" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_3pcd" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_3pcd" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_3pcd0.5" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=1 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_3pcd0.5" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2

# ablation study
# CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_offset_interval10" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_offset_interval20" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_offset_interval40" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
# CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_offset_interval10" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2
# CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_offset_interval20" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2
# CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_offset_interval40" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2

# --------------------
CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_offset_thr0.2" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_offset_thr0.4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/pulling_split3r_v4_offset_thr0.6" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/pulling_soft_tissues
CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_offset_thr0.2" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2
CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_offset_thr0.4" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2
CUDA_VISIBLE_DEVICES=2 python render.py --model_path "/suedata1/Free/xkangyu/mycodes/splatt3r_gs/output/endonerf/stereomis_p2_2_2_split3r_v4_offset_thr0.6" --pc --skip_video --skip_train --configs arguments/endonerf.py -s /suedata1/Free/xkangyu/data/dynamic_endo_scene/stereomis_p2_2_2