name: 'full_datasets_v3_inv_opticalflow_mask_weight_ep50_debug_thr0.2'

save_dir: './results/${name}/'

# Environment
seed: 42 # 0
devices: 'auto'

# Loggers
use_profiler: False
loggers:
  use_csv_logger: True
  use_wandb: False

# Model
use_pretrained: True
# pretrained_mast3r_path: './checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth'
pretrained_mast3r_path: './checkpoints/Splatt3r_pretrain.pth'

# Data
data:
  root: '/suedata1/Free/xkangyu/data/dynamic_endo_scene'
  batch_size: 16 #12
  num_workers: 16 # 16
  resolution: [640, 512]
  epochs_per_train_epoch: 150 # How many times to sample from each scene each training epoch (helps avoid unnecessary Pytorch Lightning overhead)

# Optimization
opt:
  epochs: 40
  lr: 0.000005
  weight_decay: 0.05
  gradient_clip_val: 0.5

loss:
  mse_loss_weight: 1.0
  lpips_loss_weight: 0.25
  mast3r_loss_weight: Null
  apply_mask: True
  average_over_mask: True

use_offsets: True
sh_degree: 1
optical_flow: True